oenik_prog4hf_2021_1_go10dv/Languages.Web/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Languages.Web.Models
{
    /// <summary>
    /// Country class.
    /// </summary>
    public class Country
    {
        /// <summary>
        /// Gets or sets country id.
        /// </summary>
        [Display(Name = "Country's id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets country's name.
        /// </summary>
        [StringLength(40)]
        [Required]
        [Display(Name = "Country's name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets country's population.
        /// </summary>
        [Display(Name = "Country's population")]
        public int Population { get; set; }

        /// <summary>
        /// Gets or sets country's capital.
        /// </summary>
        [StringLength(40)]
        [Required]
        [Display(Name = "Country's capital")]
        public string Capital { get; set; }

        /// <summary>
        /// Gets or sets country's continent.
        /// </summary>
        [StringLength(40)]
        [Required]
        [Display(Name = "Country's continent")]
        public string Continent { get; set; }

        /// <summary>
        /// Gets or sets country's area.
        /// </summary>
        [Display(Name = "Country's area")]
        public int Area { get; set; }
    }
}

oenik_prog4hf_2021_1_go10dv/Languages.Web/Controllers/CountriesController.cs
using AutoMapper;
using Languages.Data;
using Languages.Logic;
using Languages.Logic.Logics;
using Languages.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Languages.Web.Controllers
{
    /// <summary>
    /// Countries controller.
    /// </summary>
    public class CountriesController : Controller
    {
        private ILogic<Data.Country> logic;
        private IMapper mapper;
        private CountryListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="CountriesController"/> class.
        /// </summary>
        /// <param name="logic">Country logic.</param>
        /// <param name="mapper">Automapper.</param>
        public CountriesController(ILogic<Data.Country> logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            vm = new CountryListViewModel();
            vm.EditedCountry = new Models.Country();

            var countries = logic.GetAll().ToList();
            vm.ListOfCountries = mapper.Map<IList<Data.Country>, List<Models.Country>>(countries);
        }

        private Models.Country GetCountryModel(int id)
        {
            Data.Country oneCountry = logic.GetOne(id);
            return mapper.Map<Data.Country, Models.Country>(oneCountry);
        }

        /// <summary>
        /// GET: Countries
        /// Main page of the countries.
        /// </summary>
        /// <returns>View.</returns>
        public IActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("CountriesIndex", vm);
        }

        /// <summary>
        /// Details of a country.
        /// </summary>
        /// <param name="id">Id of the country.</param>
        /// <returns>View.</returns>
        public IActionResult Details(int id)
        {
            return View("CountriesDetails", GetCountryModel(id));
        }

        /// <summary>
        /// GET: Countries/Remove/1
        /// Remove a country.
        /// </summary>
        /// <param name="id">Id of the country.</param>
        /// <returns>View.</returns>
        public IActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete OK";

            try
            {
                logic.Remove(id);
            }
            catch (Exception)
            {
                TempData["editResult"] = "Delete FAIL";
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Edit a country.
        /// GET: Countries/Edit/1
        /// </summary>
        /// <param name="id">Id of the country.</param>
        /// <returns>View.</returns>
        public IActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedCountry = GetCountryModel(id);
            return View("CountriesIndex", vm);
        }

        /// <summary>
        /// Edit a country.
        /// POST: Countries/Edit + edit action
        /// </summary>
        /// <param name="country">Country.</param>
        /// <param name="editAction">Editing or adding.</param>
        /// <returns>View.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Country country, string editAction)
        {
            if (ModelState.IsValid && country != null)
            {
                Data.Country countryData = mapper.Map<Models.Country, Data.Country>(country);

                if (editAction == "AddNew")
                {
                    try
                    {
                        logic.Insert(countryData);
                        TempData["editResult"] = "Edit OK";
                    }
                    catch (Exception)
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                else
                {
                    try
                    {

                        logic.Modify(country.Id, countryData);
                        TempData["editResult"] = "Edit OK";
                    }
                    catch (Exception)
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedCountry = country;
                return View("CountriesIndex", vm);
            }
        }
    }
}

oenik_prog4hf_2021_1_go10dv/Languages.Web/Views/Countries/CountriesDetails.cshtml
@model Languages.Web.Models.Country

<h2>Datasheet of one country</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(c => c.Id)</td>
        <td>@Html.DisplayFor(c => c.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(c => c.Name)</td>
        <td>@Html.DisplayFor(c => c.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(c => c.Population)</td>
        <td>@Html.DisplayFor(c => c.Population)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(c => c.Capital)</td>
        <td>@Html.DisplayFor(c => c.Capital)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(c => c.Continent)</td>
        <td>@Html.DisplayFor(c => c.Continent)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(c => c.Area)</td>
        <td>@Html.DisplayFor(c => c.Area)</td>
    </tr>
</table>

oenik_prog4hf_2021_1_go10dv/Languages.Web/Views/Countries/CountriesEdit.cshtml
@model Languages.Web.Models.Country

@{
    ViewData["Title"] = "Countries Edit";
}

<h2>Countries Edit</h2>

@using (Html.BeginForm("Edit", "Countries"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(c => c.Id)

    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(c => c.Name)</div>
    <div class="editor-field">@Html.EditorFor(c => c.Name)</div>

    <div class="editor-label">@Html.LabelFor(c => c.Population)</div>
    <div class="editor-field">@Html.EditorFor(c => c.Population)</div>

    <div class="editor-label">@Html.LabelFor(c => c.Capital)</div>
    <div class="editor-field">@Html.EditorFor(c => c.Capital)</div>


    <div class="editor-label">@Html.LabelFor(c => c.Continent)</div>
    <div class="editor-field">@Html.EditorFor(c => c.Continent)</div>

    <div class="editor-label">@Html.LabelFor(c => c.Area)</div>
    <div class="editor-field">@Html.EditorFor(c => c.Area)</div>

    <input type="submit" value="SEND" />

}

oenik_prog4hf_2021_1_go10dv/Languages.Web/Views/Countries/CountriesIndex.cshtml
@model Languages.Web.Models.CountryListViewModel

@{
    ViewData["Title"] = "Countries Index";
}

<h2>Countries Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("CountriesEdit", Model.EditedCountry)

@await Html.PartialAsync("CountriesList", Model.ListOfCountries)

oenik_prog4hf_2021_1_go10dv/Languages.Web/Views/Countries/CountriesList.cshtml
@model IEnumerable<Languages.Web.Models.Country>

<h2>Countries List</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database.</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(c => c.First().Name)</th>
            <th>@Html.DisplayNameFor(c => c.First().Population)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach (var country in Model)
        {
            <tr>
                <td>@Html.DisplayFor(c => country.Name)</td>
                <td>@Html.DisplayFor(c => country.Population)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = country.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = country.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = country.Id })</td>
            </tr>
        }
    </table>   
}